### ISSUE TITLE
Any plans to publish this?

### ISSUE THREAD

**Issue by gregsymons** [alkersan/sbt-package-courier#1]
Taking a look at this, it looks pretty good and I'd like to use it. Have you published a build of it anywhere?

**Comment by alkersan** [comment]
Yes, it definitely needs to be published. It will be on bintray right after they resolve an issue with my repo.

**Comment by gregsymons** [comment]
Cool. 'Til then, I'll just pull it as source. Do you mind leaving this open until it is, so I can just watch the issue?

**Comment by alkersan** [comment]
released to bintray and linked with sbt organization
